"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions */
import { AlertTriangle, Info, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { useLocalCollection } from "@/lib/use-local-collection";
import { Field, ModalActions, ModalHeader } from "@/features/observations/observations-page-client";
import { useI18n } from "@/i18n/i18n-provider";
import { ruleTypes, severities, type InvestmentRule } from "./types";

export function RulesPageClient() {
  const { t, formatNumber } = useI18n();
  const store = useLocalCollection<InvestmentRule>("rules", []); const [editing, setEditing] = useState<InvestmentRule | "new" | null>(null);
  return <><div className="flex items-end justify-between"><div><p className="text-sm text-[var(--muted)]">{t("매매를 막지 않고 위반 가능성을 알려줍니다")}</p><h1 className="mt-1 text-2xl font-semibold">{t("투자 원칙")}</h1></div><button onClick={() => setEditing("new")} className="flex items-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm text-white"><Plus size={17} />{t("원칙 추가")}</button></div><div className="mt-6 space-y-3">{store.items.map((rule) => <article key={rule.id} className="flex flex-wrap items-center gap-4 rounded-xl border bg-[var(--surface)] p-5"><div className={`grid size-10 place-items-center rounded-lg ${rule.severity === "경고" ? "bg-red-50 text-red-600" : rule.severity === "주의" ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-600"}`}>{rule.severity === "경고" ? <AlertTriangle size={19} /> : rule.severity === "주의" ? <ShieldCheck size={19} /> : <Info size={19} />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{rule.title}</h2><span className="rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs">{t(rule.ruleType)}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{rule.description}</p>{rule.thresholdValue != null && <p className="mt-2 text-xs font-medium text-[var(--accent)]">{t("기준 {value}{unit}", { value: formatNumber(rule.thresholdValue), unit: rule.thresholdUnit })}</p>}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.isActive} onChange={(e) => store.update({ ...rule, isActive: e.target.checked, updatedAt: new Date().toISOString() })} />{t("활성")}</label><button onClick={() => setEditing(rule)} className="rounded-lg border px-3 py-2 text-sm">{t("수정")}</button><button aria-label={t("{title} 삭제", { title: rule.title })} onClick={() => store.remove(rule.id)} className="grid size-9 place-items-center text-red-600"><Trash2 size={16} /></button></article>)}</div>{editing && <RuleForm value={editing === "new" ? undefined : editing} cancel={() => setEditing(null)} save={(rule) => { editing === "new" ? store.add(rule) : store.update(rule); setEditing(null); }} />}</>;
}
function RuleForm({ value, cancel, save }: { value?: InvestmentRule; cancel: () => void; save: (value: InvestmentRule) => void }) { const { t } = useI18n(); const [form, setForm] = useState(() => value ?? ({ title: "", description: "", ruleType: "사용자 정의", thresholdValue: null, thresholdUnit: "", isActive: true, severity: "주의" } as unknown as InvestmentRule)); const set = (key: keyof InvestmentRule, next: unknown) => setForm((old) => ({ ...old, [key]: next })); const input = "mt-1 h-10 w-full rounded-lg border bg-[var(--surface)] px-3 text-sm"; return <div className="fixed inset-0 z-50 flex justify-end bg-black/35"><form className="h-full w-full max-w-lg bg-[var(--surface)]" onSubmit={(e) => { e.preventDefault(); const now = new Date().toISOString(); save({ ...form, id: value?.id ?? crypto.randomUUID(), createdAt: value?.createdAt ?? now, updatedAt: now, deletedAt: null }); }}><ModalHeader title={t(value ? "원칙 수정" : "투자 원칙 추가")} close={cancel} /><div className="space-y-5 p-5"><Field label={t("제목")}><input required className={input} value={form.title} onChange={(e) => set("title", e.target.value)} /></Field><Field label={t("설명")}><textarea className="mt-1 min-h-24 w-full rounded-lg border p-3 text-sm" value={form.description} onChange={(e) => set("description", e.target.value)} /></Field><Field label={t("원칙 유형")}><select className={input} value={form.ruleType} onChange={(e) => set("ruleType", e.target.value)}>{ruleTypes.map((v) => <option key={v} value={v}>{t(v)}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label={t("기준값")}><input type="number" step="any" className={input} value={form.thresholdValue ?? ""} onChange={(e) => set("thresholdValue", e.target.value ? Number(e.target.value) : null)} /></Field><Field label={t("단위")}><input className={input} value={form.thresholdUnit} onChange={(e) => set("thresholdUnit", e.target.value)} /></Field></div><Field label={t("심각도")}><select className={input} value={form.severity} onChange={(e) => set("severity", e.target.value)}>{severities.map((v) => <option key={v} value={v}>{t(v)}</option>)}</select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => set("isActive", e.target.checked)} />{t("활성화")}</label></div><ModalActions cancel={cancel} /></form></div>; }
