"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions */
import { CheckCircle2, Pencil, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { sampleStocks } from "@/features/stocks/sample-data";
import { useLocalCollection } from "@/lib/use-local-collection";
import { Field, ModalActions, ModalHeader } from "@/features/observations/observations-page-client";
import { sampleReviews } from "./sample-data";
import { reviewEvaluations, type Review } from "./types";

export function ReviewsPageClient() {
  const store = useLocalCollection("reviews", sampleReviews); const [editing, setEditing] = useState<Review | "new" | null>(null);
  return <><div className="flex items-end justify-between"><div><p className="text-sm text-[var(--muted)]">결과와 과정의 질을 분리해서 평가</p><h1 className="mt-1 text-2xl font-semibold">회고</h1></div><button onClick={() => setEditing("new")} className="flex items-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm text-white"><Plus size={17} />회고 작성</button></div><section className="mt-6 grid gap-4 xl:grid-cols-2">{store.items.map((review) => <article key={review.id} className="rounded-xl border bg-[var(--surface)] p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-[var(--accent)]">{review.stockName} · {review.reviewedAt}</p><h2 className="mt-2 font-semibold">{review.evaluation}</h2></div><div className="flex"><button aria-label="회고 수정" onClick={() => setEditing(review)} className="grid size-8 place-items-center"><Pencil size={15} /></button><button aria-label="회고 삭제" onClick={() => store.remove(review.id)} className="grid size-8 place-items-center text-red-600"><Trash2 size={15} /></button></div></div><div className="mt-4 grid grid-cols-2 gap-3"><Score label="결과 점수" value={review.resultScore} /><Score label="과정 점수" value={review.processScore} /></div><p className="mt-4 text-sm leading-6"><b>결과</b> · {review.result || "미기록"}</p><p className="mt-2 text-sm leading-6"><b>배운 점</b> · {review.lessons || "미기록"}</p><div className="mt-4 flex items-center gap-2 border-t pt-3 text-xs text-[var(--muted)]"><CheckCircle2 size={14} className={review.planCompliance ? "text-emerald-600" : "text-red-600"} />계획 {review.planCompliance ? "준수" : "미준수"} · 감정 {review.emotionState}</div></article>)}</section>{editing && <ReviewForm value={editing === "new" ? undefined : editing} cancel={() => setEditing(null)} save={(value) => { editing === "new" ? store.add(value) : store.update(value); setEditing(null); }} />}</>;
}
function Score({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-[var(--surface-muted)] p-3"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-1 text-lg font-semibold">{value}<small className="text-xs text-[var(--muted)]"> / 5</small></p></div>; }

function ReviewForm({ value, cancel, save }: { value?: Review; cancel: () => void; save: (value: Review) => void }) {
  const [form, setForm] = useState(() => value ?? ({ stockId: "micron", reviewedAt: new Date().toISOString().slice(0, 10), result: "", decisionQuality: "", executionQuality: "", planCompliance: true, emotionState: "평온", strengths: "", mistakes: "", nextAction: "", lessons: "", evaluation: "좋은 판단, 좋은 결과", resultScore: 3, processScore: 3 } as unknown as Review)); const set = (key: keyof Review, next: unknown) => setForm((old) => ({ ...old, [key]: next })); const input = "mt-1 h-10 w-full rounded-lg border bg-[var(--surface)] px-3 text-sm";
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/35"><form className="h-full w-full max-w-2xl overflow-y-auto bg-[var(--surface)]" onSubmit={(e) => { e.preventDefault(); const stock = sampleStocks.find((s) => s.id === form.stockId)!; const now = new Date().toISOString(); save({ ...form, id: value?.id ?? crypto.randomUUID(), stockName: stock.name, tradeId: value?.tradeId ?? null, createdAt: value?.createdAt ?? now, updatedAt: now, deletedAt: null }); }}><ModalHeader title={value ? "회고 수정" : "새 회고"} close={cancel} /><div className="grid gap-5 p-5 sm:grid-cols-2"><Field label="종목"><select className={input} value={form.stockId} onChange={(e) => set("stockId", e.target.value)}>{sampleStocks.map((s) => <option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="회고일"><input type="date" className={input} value={form.reviewedAt} onChange={(e) => set("reviewedAt", e.target.value)} /></Field><div className="sm:col-span-2"><Field label="평가"><select className={input} value={form.evaluation} onChange={(e) => set("evaluation", e.target.value)}>{reviewEvaluations.map((v) => <option key={v}>{v}</option>)}</select></Field></div><Text label="결과" value={form.result} change={(v) => set("result", v)} /><Text label="판단의 질" value={form.decisionQuality} change={(v) => set("decisionQuality", v)} /><Text label="실행의 질" value={form.executionQuality} change={(v) => set("executionQuality", v)} /><Text label="잘한 점" value={form.strengths} change={(v) => set("strengths", v)} /><Text label="잘못한 점" value={form.mistakes} change={(v) => set("mistakes", v)} /><Text label="다시 같은 상황이 오면" value={form.nextAction} change={(v) => set("nextAction", v)} /><div className="sm:col-span-2"><Text label="배운 점" value={form.lessons} change={(v) => set("lessons", v)} /></div><Field label="결과 점수"><input type="range" min="1" max="5" value={form.resultScore} onChange={(e) => set("resultScore", Number(e.target.value))} className="mt-2 w-full" /><span className="text-xs">{form.resultScore}/5</span></Field><Field label="과정 점수"><input type="range" min="1" max="5" value={form.processScore} onChange={(e) => set("processScore", Number(e.target.value))} className="mt-2 w-full" /><span className="text-xs">{form.processScore}/5</span></Field><Field label="감정 상태"><input className={input} value={form.emotionState} onChange={(e) => set("emotionState", e.target.value)} /></Field><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={form.planCompliance} onChange={(e) => set("planCompliance", e.target.checked)} />계획을 준수함</label></div><ModalActions cancel={cancel} /></form></div>;
}
function Text({ label, value, change }: { label: string; value: string; change: (value: string) => void }) { return <Field label={label}><textarea className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" value={value} onChange={(e) => change(e.target.value)} /></Field>; }
