import type { MessageCatalog } from "../types";
const escapedAliases = {
  "현재 기록에 샘플 데이터를 추가할까요?\\n\\n기존 데이터는 변경되지 않습니다. 가상의 계좌, 종목, 매매, 계획, 관찰 및 회고가 추가됩니다.": "Add sample data to current records?",
  "샘플 데이터를 제거할까요?\\n\\n샘플 데이터에 직접 수정한 내용도 함께 제거됩니다. 직접 추가한 데이터는 삭제되지 않습니다.": "Remove sample data?",
};
export const sampleEscapedMessages: MessageCatalog = { en: escapedAliases, ja: escapedAliases, fr: escapedAliases, it: escapedAliases, es: escapedAliases };
const en = { "샘플 데이터": "Sample data", "샘플 데이터 불러오기": "Load sample data", "샘플 데이터 제거": "Remove sample data", "샘플 데이터로 둘러보기": "Explore with sample data", "누락된 샘플 데이터 추가": "Add missing sample data", "현재 샘플 데이터가 포함되어 있습니다.": "Sample data is currently installed.", "일부 샘플 데이터가 존재합니다.": "Some sample data is present.", "샘플 데이터가 없습니다.": "No sample data is installed.", "샘플 데이터 상태 확인 중": "Checking sample data status", "아직 투자 기록이 없습니다.": "No investment records yet.", "첫 종목 추가": "Add first stock", "첫 종목을 추가하거나 가상의 샘플 데이터로 주요 기능을 둘러보세요.": "Add your first stock or explore the main features with fictional sample data.", "Rationale의 주요 기능을 둘러볼 수 있는 가상의 투자 기록을 추가합니다. 기존 기록은 변경하지 않습니다.": "Add fictional investment records that demonstrate Rationale's main features. Existing records are not changed.", "샘플 데이터를 추가했습니다.": "Sample data added.", "샘플 데이터를 제거했습니다.": "Sample data removed.", "샘플 데이터를 추가하지 못했습니다.": "Could not add sample data.", "샘플 데이터를 제거하지 못했습니다.": "Could not remove sample data.", "샘플 데이터 상태를 확인하지 못했습니다.": "Could not check sample data status.", "손상된 데이터를 먼저 복구한 뒤 샘플 데이터를 추가해 주세요.": "Recover the corrupted data before adding sample data.", "직접 작성한 기록이 샘플 종목 또는 계좌에 연결되어 있어 샘플 데이터를 제거할 수 없습니다. 연결된 기록을 먼저 정리해 주세요.": "Sample data cannot be removed because your records reference a sample stock or account. Remove those links first.", "샘플 데이터로 Rationale을 둘러볼까요? 기존 데이터는 변경되지 않습니다.": "Explore Rationale with sample data? Existing data will not be changed.", "현재 기록에 샘플 데이터를 추가할까요?\n\n기존 데이터는 변경되지 않습니다. 가상의 계좌, 종목, 매매, 계획, 관찰 및 회고가 추가됩니다.": "Add sample data to your current records?\n\nExisting data will not be changed. Fictional accounts, stocks, trades, plans, observations, and reviews will be added.", "샘플 데이터를 제거할까요?\n\n샘플 데이터에 직접 수정한 내용도 함께 제거됩니다. 직접 추가한 데이터는 삭제되지 않습니다.": "Remove sample data?\n\nEdits made directly to sample records will also be removed. Your own data will not be deleted." };
export const sampleDataMessages: MessageCatalog = {
  en,
  ja: { ...en, "샘플 데이터": "サンプルデータ", "샘플 데이터 불러오기": "サンプルデータを読み込む", "샘플 데이터 제거": "サンプルデータを削除", "샘플 데이터로 둘러보기": "サンプルデータで見る", "아직 투자 기록이 없습니다.": "投資記録はまだありません。" },
  fr: { ...en, "샘플 데이터": "Données d’exemple", "샘플 데이터 불러오기": "Charger les données d’exemple", "샘플 데이터 제거": "Supprimer les données d’exemple", "샘플 데이터로 둘러보기": "Explorer avec des exemples", "아직 투자 기록이 없습니다.": "Aucun investissement pour le moment." },
  it: { ...en, "샘플 데이터": "Dati di esempio", "샘플 데이터 불러오기": "Carica dati di esempio", "샘플 데이터 제거": "Rimuovi dati di esempio", "샘플 데이터로 둘러보기": "Esplora con dati di esempio", "아직 투자 기록이 없습니다.": "Non ci sono ancora investimenti." },
  es: { ...en, "샘플 데이터": "Datos de ejemplo", "샘플 데이터 불러오기": "Cargar datos de ejemplo", "샘플 데이터 제거": "Eliminar datos de ejemplo", "샘플 데이터로 둘러보기": "Explorar con datos de ejemplo", "아직 투자 기록이 없습니다.": "Aún no hay inversiones." },
};
