import type { MessageCatalog } from "../types";

export const stockAccountMessages: MessageCatalog = {
  ja: {
    "보유 계좌": "保有口座", "보유 계좌: {accounts}": "保有口座：{accounts}", "현재 보유 계좌가 없습니다.": "現在保有している口座はありません。", "{name} 외 {count}": "{name}、ほか{count}件",
    "보유 계좌·수량·평균단가는 종목 추가 후 매매 원장에서 등록합니다.": "保有口座・数量・平均取得単価は、銘柄追加後に取引台帳で登録します。", "현재 보유 포지션이 없습니다.": "現在保有しているポジションはありません。", "계좌와 보유 수량은 매매 원장에서 관리됩니다.": "口座と保有数量は取引台帳で管理されます。", "매매 원장 열기": "取引台帳を開く",
    "기존 보유 정보": "既存の保有情報", "기초 계좌": "開始口座", "기초 수량": "開始数量", "기초 평균단가": "開始平均取得単価", "매매 원장 전환 전의 기존 보유 기록입니다.": "取引台帳への移行前に記録された既存の保有情報です。",
    "기존 매매 통화 {currency}에 맞춰 종목 통화를 변경할 수 있습니다.": "既存の取引通貨{currency}に合わせて銘柄の通貨を変更できます。", "여러 통화의 매매 기록이 있어 종목 통화를 변경할 수 없습니다.": "複数通貨の取引記録があるため、銘柄の通貨は変更できません。",
    "통화를 변경하면 기존 매수·매도 기록의 통화와 거래일 환율을 다시 적용합니다.": "通貨を変更すると、既存の売買取引の通貨と取引日の為替レートが再適用されます。", "종목 통화를 변경할까요?": "銘柄の通貨を変更しますか？", "통화 변경": "通貨を変更", "영향받는 매매 기록": "影響を受ける取引", "영향받는 계좌": "影響を受ける口座", "가격 숫자는 환산하지 않습니다.": "価格の数値自体は換算しません。", "기존 매수·매도의 통화가 {currency}(으)로 변경됩니다.": "既存の売買取引の通貨が{currency}に変更されます。", "각 거래일의 과거 환율을 다시 적용합니다.": "各取引日の過去為替レートを再適用します。", "원화 기준 투자원금과 손익이 다시 계산됩니다.": "KRW基準の投資元本と損益が再計算されます。", "이 종목에는 서로 다른 통화의 매매 기록이 있어 통화를 자동으로 변경할 수 없습니다. 매매 기록의 통화를 먼저 확인해 주세요.": "この銘柄には異なる通貨の取引があるため、自動変更できません。先に取引通貨を確認してください。", "{date} 거래의 과거 환율을 확인하지 못해 통화를 변경하지 않았습니다.": "{date}の取引の過去為替レートを確認できなかったため、通貨は変更されませんでした。", "통화를 변경하지 못했습니다.": "通貨を変更できませんでした。",
  },
  en: {
    "보유 계좌": "Holding accounts", "보유 계좌: {accounts}": "Holding accounts: {accounts}", "현재 보유 계좌가 없습니다.": "There are no current holding accounts.", "{name} 외 {count}": "{name} +{count}",
    "보유 계좌·수량·평균단가는 종목 추가 후 매매 원장에서 등록합니다.": "Add holding accounts, quantities, and average costs in the trade ledger after adding the stock.", "현재 보유 포지션이 없습니다.": "There are no open positions.", "계좌와 보유 수량은 매매 원장에서 관리됩니다.": "Accounts and quantities held are managed in the trade ledger.", "매매 원장 열기": "Open trade ledger",
    "기존 보유 정보": "Legacy holding information", "기초 계좌": "Opening account", "기초 수량": "Opening quantity", "기초 평균단가": "Opening average cost", "매매 원장 전환 전의 기존 보유 기록입니다.": "This holding was recorded before migration to the trade ledger.",
    "기존 매매 통화 {currency}에 맞춰 종목 통화를 변경할 수 있습니다.": "You can align the stock currency with the existing trade currency, {currency}.", "여러 통화의 매매 기록이 있어 종목 통화를 변경할 수 없습니다.": "The stock currency cannot be changed because its trades use multiple currencies.",
    "통화를 변경하면 기존 매수·매도 기록의 통화와 거래일 환율을 다시 적용합니다.": "Changing the currency reapplies it to existing buys and sells together with each trade date’s FX rate.", "종목 통화를 변경할까요?": "Change the stock currency?", "통화 변경": "Change currency", "영향받는 매매 기록": "Affected trades", "영향받는 계좌": "Affected accounts", "가격 숫자는 환산하지 않습니다.": "Price numbers are not converted.", "기존 매수·매도의 통화가 {currency}(으)로 변경됩니다.": "Existing buys and sells will use {currency}.", "각 거래일의 과거 환율을 다시 적용합니다.": "Historical FX rates will be reapplied for each trade date.", "원화 기준 투자원금과 손익이 다시 계산됩니다.": "KRW-denominated invested capital and profit will be recalculated.", "이 종목에는 서로 다른 통화의 매매 기록이 있어 통화를 자동으로 변경할 수 없습니다. 매매 기록의 통화를 먼저 확인해 주세요.": "This stock has trades in different currencies, so its currency cannot be changed automatically. Review the trade currencies first.", "{date} 거래의 과거 환율을 확인하지 못해 통화를 변경하지 않았습니다.": "The currency was not changed because the historical FX rate for the {date} trade could not be verified.", "통화를 변경하지 못했습니다.": "Could not change the currency.",
  },
  fr: {
    "보유 계좌": "Comptes de détention", "보유 계좌: {accounts}": "Comptes de détention : {accounts}", "현재 보유 계좌가 없습니다.": "Aucun compte ne détient actuellement ce titre.", "{name} 외 {count}": "{name} +{count}",
    "보유 계좌·수량·평균단가는 종목 추가 후 매매 원장에서 등록합니다.": "Ajoutez les comptes, quantités et prix moyens dans le registre des transactions après avoir ajouté le titre.", "현재 보유 포지션이 없습니다.": "Aucune position ouverte.", "계좌와 보유 수량은 매매 원장에서 관리됩니다.": "Les comptes et quantités détenues sont gérés dans le registre des transactions.", "매매 원장 열기": "Ouvrir le registre des transactions",
    "기존 보유 정보": "Informations de détention antérieures", "기초 계좌": "Compte initial", "기초 수량": "Quantité initiale", "기초 평균단가": "Prix moyen initial", "매매 원장 전환 전의 기존 보유 기록입니다.": "Cette détention a été enregistrée avant la migration vers le registre des transactions.",
    "기존 매매 통화 {currency}에 맞춰 종목 통화를 변경할 수 있습니다.": "Vous pouvez aligner la devise du titre sur celle des transactions existantes : {currency}.", "여러 통화의 매매 기록이 있어 종목 통화를 변경할 수 없습니다.": "La devise du titre ne peut pas être modifiée car ses transactions utilisent plusieurs devises.",
    "통화를 변경하면 기존 매수·매도 기록의 통화와 거래일 환율을 다시 적용합니다.": "La modification de la devise la réapplique aux achats et ventes existants avec le taux de change de chaque date.", "종목 통화를 변경할까요?": "Modifier la devise du titre ?", "통화 변경": "Modifier la devise", "영향받는 매매 기록": "Transactions concernées", "영향받는 계좌": "Comptes concernés", "가격 숫자는 환산하지 않습니다.": "Les valeurs de prix ne sont pas converties.", "기존 매수·매도의 통화가 {currency}(으)로 변경됩니다.": "Les achats et ventes existants passeront en {currency}.", "각 거래일의 과거 환율을 다시 적용합니다.": "Le taux historique de chaque date de transaction sera réappliqué.", "원화 기준 투자원금과 손익이 다시 계산됩니다.": "Le capital investi et le résultat en KRW seront recalculés.", "이 종목에는 서로 다른 통화의 매매 기록이 있어 통화를 자동으로 변경할 수 없습니다. 매매 기록의 통화를 먼저 확인해 주세요.": "Ce titre comporte des transactions en devises différentes. Vérifiez d’abord leurs devises.", "{date} 거래의 과거 환율을 확인하지 못해 통화를 변경하지 않았습니다.": "La devise n’a pas été modifiée car le taux historique de la transaction du {date} n’a pas pu être vérifié.", "통화를 변경하지 못했습니다.": "Impossible de modifier la devise.",
  },
  it: {
    "보유 계좌": "Conti di detenzione", "보유 계좌: {accounts}": "Conti di detenzione: {accounts}", "현재 보유 계좌가 없습니다.": "Nessun conto detiene attualmente questo titolo.", "{name} 외 {count}": "{name} +{count}",
    "보유 계좌·수량·평균단가는 종목 추가 후 매매 원장에서 등록합니다.": "Aggiungi conti, quantità e prezzi medi nel registro operazioni dopo aver aggiunto il titolo.", "현재 보유 포지션이 없습니다.": "Non ci sono posizioni aperte.", "계좌와 보유 수량은 매매 원장에서 관리됩니다.": "I conti e le quantità detenute sono gestiti nel registro operazioni.", "매매 원장 열기": "Apri registro operazioni",
    "기존 보유 정보": "Informazioni di detenzione precedenti", "기초 계좌": "Conto iniziale", "기초 수량": "Quantità iniziale", "기초 평균단가": "Prezzo medio iniziale", "매매 원장 전환 전의 기존 보유 기록입니다.": "Questa detenzione è stata registrata prima della migrazione al registro operazioni.",
    "기존 매매 통화 {currency}에 맞춰 종목 통화를 변경할 수 있습니다.": "Puoi allineare la valuta del titolo alla valuta delle operazioni esistenti, {currency}.", "여러 통화의 매매 기록이 있어 종목 통화를 변경할 수 없습니다.": "La valuta del titolo non può essere modificata perché le operazioni usano più valute.",
    "통화를 변경하면 기존 매수·매도 기록의 통화와 거래일 환율을 다시 적용합니다.": "La modifica della valuta la riapplica agli acquisti e alle vendite esistenti con il cambio di ogni data.", "종목 통화를 변경할까요?": "Modificare la valuta del titolo?", "통화 변경": "Modifica valuta", "영향받는 매매 기록": "Operazioni interessate", "영향받는 계좌": "Conti interessati", "가격 숫자는 환산하지 않습니다.": "I valori numerici dei prezzi non vengono convertiti.", "기존 매수·매도의 통화가 {currency}(으)로 변경됩니다.": "Gli acquisti e le vendite esistenti passeranno a {currency}.", "각 거래일의 과거 환율을 다시 적용합니다.": "Verrà riapplicato il cambio storico di ogni data di negoziazione.", "원화 기준 투자원금과 손익이 다시 계산됩니다.": "Capitale investito e profitti in KRW verranno ricalcolati.", "이 종목에는 서로 다른 통화의 매매 기록이 있어 통화를 자동으로 변경할 수 없습니다. 매매 기록의 통화를 먼저 확인해 주세요.": "Questo titolo ha operazioni in valute diverse. Controlla prima le valute delle operazioni.", "{date} 거래의 과거 환율을 확인하지 못해 통화를 변경하지 않았습니다.": "La valuta non è stata modificata perché non è stato possibile verificare il cambio storico dell’operazione del {date}.", "통화를 변경하지 못했습니다.": "Impossibile modificare la valuta.",
  },
  es: {
    "보유 계좌": "Cuentas de tenencia", "보유 계좌: {accounts}": "Cuentas de tenencia: {accounts}", "현재 보유 계좌가 없습니다.": "Ninguna cuenta mantiene actualmente este valor.", "{name} 외 {count}": "{name} +{count}",
    "보유 계좌·수량·평균단가는 종목 추가 후 매매 원장에서 등록합니다.": "Añade las cuentas, cantidades y precios medios en el registro de operaciones después de añadir el valor.", "현재 보유 포지션이 없습니다.": "No hay posiciones abiertas.", "계좌와 보유 수량은 매매 원장에서 관리됩니다.": "Las cuentas y cantidades se gestionan en el registro de operaciones.", "매매 원장 열기": "Abrir registro de operaciones",
    "기존 보유 정보": "Información de tenencia anterior", "기초 계좌": "Cuenta inicial", "기초 수량": "Cantidad inicial", "기초 평균단가": "Precio medio inicial", "매매 원장 전환 전의 기존 보유 기록입니다.": "Esta tenencia se registró antes de migrar al registro de operaciones.",
    "기존 매매 통화 {currency}에 맞춰 종목 통화를 변경할 수 있습니다.": "Puedes alinear la moneda del valor con la moneda de las operaciones existentes, {currency}.", "여러 통화의 매매 기록이 있어 종목 통화를 변경할 수 없습니다.": "La moneda del valor no se puede cambiar porque sus operaciones usan varias monedas.",
    "통화를 변경하면 기존 매수·매도 기록의 통화와 거래일 환율을 다시 적용합니다.": "Al cambiar la moneda, se reaplica a las compras y ventas existentes junto con el cambio de cada fecha.", "종목 통화를 변경할까요?": "¿Cambiar la moneda del valor?", "통화 변경": "Cambiar moneda", "영향받는 매매 기록": "Operaciones afectadas", "영향받는 계좌": "Cuentas afectadas", "가격 숫자는 환산하지 않습니다.": "Los valores numéricos de los precios no se convierten.", "기존 매수·매도의 통화가 {currency}(으)로 변경됩니다.": "Las compras y ventas existentes pasarán a {currency}.", "각 거래일의 과거 환율을 다시 적용합니다.": "Se reaplicará el cambio histórico de cada fecha de operación.", "원화 기준 투자원금과 손익이 다시 계산됩니다.": "El capital invertido y el resultado en KRW se recalcularán.", "이 종목에는 서로 다른 통화의 매매 기록이 있어 통화를 자동으로 변경할 수 없습니다. 매매 기록의 통화를 먼저 확인해 주세요.": "Este valor tiene operaciones en distintas monedas. Revisa primero las monedas de las operaciones.", "{date} 거래의 과거 환율을 확인하지 못해 통화를 변경하지 않았습니다.": "La moneda no se cambió porque no se pudo verificar el cambio histórico de la operación del {date}.", "통화를 변경하지 못했습니다.": "No se pudo cambiar la moneda.",
  },
};
