"use client";
import { BookOpenCheck, CalendarRange } from "lucide-react";
import { useMemo, useState } from "react";
import { buildPeriodicReport, listReportPeriods, periodKey, type ReportPeriod } from "@/domain/periodic-report";
import type { TradingLedger } from "@/domain/trading-ledger";
import type { Review } from "@/features/reviews/types";
import type { Trade } from "@/features/trades/types";

export function PeriodicReportSection({ trades, reviews, ledger }: { trades: Trade[]; reviews: Review[]; ledger: TradingLedger }) {
  const [period, setPeriod] = useState<ReportPeriod>("week");
  const [selected, setSelected] = useState("");
  const periods = useMemo(() => listReportPeriods(period, trades, reviews), [period, reviews, trades]);
  const fallback = periodKey(period, new Date().toISOString());
  const key = periods.includes(selected) ? selected : periods[0] ?? fallback;
  const report = buildPeriodicReport(period, key, trades, reviews, ledger);
  const metrics = [["매매 기록", `${report.tradeCount}건`], ["실현손익", won(report.realizedProfitKrw)], ["완결 승률", report.closedCount ? `${report.winRate.toFixed(1)}%` : "—"], ["계획 매매율", report.tradeCount ? `${report.plannedTradeRate.toFixed(1)}%` : "—"], ["원칙 위반", `${report.violationCount}건`], ["작성한 회고", `${report.reviewCount}건`]];
  function changePeriod(next: ReportPeriod) { setPeriod(next); setSelected(""); }
  return <section className="mt-4 rounded-xl border bg-[var(--surface)] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><CalendarRange size={19} /></span><div><h2 className="font-semibold">주간·월간 리포트</h2><p className="mt-1 text-sm text-[var(--muted)]">성과와 반복된 실수를 한 번에 돌아봅니다.</p></div></div><div className="flex flex-wrap gap-2"><div className="flex rounded-lg bg-[var(--surface-muted)] p-1">{(["week", "month"] as const).map((item) => <button key={item} type="button" onClick={() => changePeriod(item)} className={`rounded-md px-3 py-1.5 text-sm ${period === item ? "bg-[var(--surface)] font-medium shadow-sm" : "text-[var(--muted)]"}`}>{item === "week" ? "주간" : "월간"}</button>)}</div><select aria-label="리포트 기간" value={key} onChange={(event) => setSelected(event.target.value)} className="h-10 rounded-lg border bg-[var(--surface)] px-3 text-sm">{periods.length ? periods.map((item) => <option key={item} value={item}>{buildPeriodicReport(period, item, trades, reviews, ledger).label}</option>) : <option value={key}>{report.label}</option>}</select></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metrics.map(([label, value]) => <div key={label} className="rounded-lg bg-[var(--surface-muted)] p-4"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-2 font-semibold tabular-nums">{value}</p></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-3"><article className="rounded-lg border p-4"><p className="text-xs text-[var(--muted)]">최고 성과 종목</p><p className="mt-2 font-semibold">{report.bestStock ?? "기록 없음"}</p>{report.bestStock && <p className={`mt-1 text-sm ${report.bestStockProfitKrw < 0 ? "text-red-600" : "text-emerald-600"}`}>{won(report.bestStockProfitKrw)}</p>}</article><article className="rounded-lg border p-4"><p className="text-xs text-[var(--muted)]">반복된 실수 태그</p><div className="mt-2 flex flex-wrap gap-2">{report.mistakeTags.slice(0, 5).map((item) => <span key={item.tag} className="rounded-full bg-red-50 px-2 py-1 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-200">{item.tag} {item.count}</span>)}{!report.mistakeTags.length && <span className="text-sm text-[var(--muted)]">기록 없음</span>}</div></article><article className="rounded-lg border p-4"><div className="flex items-center gap-2"><BookOpenCheck size={15} className="text-[var(--accent)]" /><p className="text-xs text-[var(--muted)]">이번 기간 배운 점</p></div><ul className="mt-2 space-y-1 text-sm">{report.lessons.slice(0, 3).map((lesson) => <li key={lesson}>· {lesson}</li>)}{!report.lessons.length && <li className="text-[var(--muted)]">작성된 회고가 없습니다.</li>}</ul></article></div></section>;
}
function won(value: number) { return new Intl.NumberFormat("ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 }).format(value); }
