import { describe, expect, it, vi } from "vitest";
import { buildLongTermPerformance } from "@/domain/account-performance";
import { buildTradingLedger } from "@/domain/trading-ledger";
import type { Trade } from "@/features/trades/types";
import { buildAccountTransfer, deleteAccountTransfer, getTransferPair, saveAccountTransfer, updateAccountTransfer, validateTransferPairs } from "./account-transfer";
import type { InvestmentAccount } from "./types";

const now="2026-01-01T00:00:00.000Z";
const accounts:InvestmentAccount[]=["a","b"].map((id,index)=>({id,name:id.toUpperCase(),institution:"",kind:"brokerage",subtype:"",baseCurrency:"KRW",isDefault:index===0,archivedAt:null,memo:"",createdAt:now,updatedAt:now}));
const cash=(id:string,accountId:string,type:"입금"|"출금",amount:number,kind?:Trade["cashFlowKind"]):Trade=>({id,stockId:null,stockName:"",planId:null,tradeType:type,tradedAt:now,quantity:0,price:0,amount,currency:"KRW",exchangeRate:1,fee:0,tax:0,accountId,accountName:accountId.toUpperCase(),cashFlowKind:kind,memo:"",emotion:"평온",emotionIntensity:1,confidenceScore:3,ruleComplianceScore:5,createdAt:now,updatedAt:now,deletedAt:null});
const rates={KRW:1,USD:1400,JPY:9,EUR:1600};

describe("cash flow semantics",()=>{
 it("reconciliation changes cash but creates neither contributions nor profit",()=>{const trades=[cash("r","a","입금",30000,"reconciliation")];const ledger=buildTradingLedger(trades,accounts);const result=buildLongTermPerformance(trades,[],ledger,rates,new Date("2027-01-01"),accounts);expect(ledger.cashBalances[0].balance).toBe(30000);expect(result.netContributionsKrw).toBe(0);expect(result.reconciliationAdjustmentKrw).toBe(30000);expect(result.totalProfitKrw).toBe(0);expect(result.xirrPercent).toBeNull();});
 it("neutralizes reconciliation deposits and withdrawals in profit and XIRR",()=>{for(const adjustment of [{type:"입금" as const,amount:30000,assets:130000},{type:"출금" as const,amount:20000,assets:80000}]){const trades=[cash("d","a","입금",100000,"external"),{...cash("r","a",adjustment.type,adjustment.amount,"reconciliation"),tradedAt:"2026-06-01T00:00:00.000Z"}];const result=buildLongTermPerformance(trades,[],buildTradingLedger(trades,accounts),rates,new Date("2027-01-01"),accounts);expect(result.totalAssetsKrw).toBe(adjustment.assets);expect(result.netContributionsKrw).toBe(100000);expect(result.totalProfitKrw).toBe(0);expect(result.xirrPercent).toBeCloseTo(0,5);}});
 it("keeps real gains when reconciliation is also present",()=>{const dividend={...cash("gain","a","입금",20000),tradeType:"배당" as const,stockId:"stock",stockName:"Stock",cashFlowKind:undefined};const trades=[cash("d","a","입금",100000,"external"),cash("r","a","입금",30000,"reconciliation"),dividend];const result=buildLongTermPerformance(trades,[],buildTradingLedger(trades,accounts),rates,new Date("2027-01-01"),accounts);expect(result.totalAssetsKrw).toBe(150000);expect(result.netContributionsKrw).toBe(100000);expect(result.totalProfitKrw).toBe(20000);});
 it("legacy external deposit increases cash and contributions",()=>{const trades=[cash("d","a","입금",100000)];const ledger=buildTradingLedger(trades,accounts);const result=buildLongTermPerformance(trades,[],ledger,rates,new Date("2027-01-01"),accounts);expect(result.cashKrw).toBe(100000);expect(result.netContributionsKrw).toBe(100000);});
 it("transfer preserves portfolio cash and aggregate contributions but affects each account",()=>{const opening=cash("d","a","입금",100000,"external");const pair=buildAccountTransfer(accounts,{sourceAccountId:"a",targetAccountId:"b",amount:40000,currency:"KRW",tradedAt:now,memo:""},now,"t");const trades=[opening,...pair];const ledger=buildTradingLedger(trades,accounts);const result=buildLongTermPerformance(trades,[],ledger,rates,new Date("2027-01-01"),accounts);expect(result.cashKrw).toBe(100000);expect(result.netContributionsKrw).toBe(100000);expect(result.accounts.find(a=>a.accountId==="a")?.netContributionsKrw).toBe(60000);expect(result.accounts.find(a=>a.accountId==="b")?.netContributionsKrw).toBe(40000);});
 it("rejects invalid transfers and writes the pair in one collection save",async()=>{expect(()=>buildAccountTransfer(accounts,{sourceAccountId:"a",targetAccountId:"a",amount:1,currency:"KRW",tradedAt:now,memo:""})).toThrow();const save=vi.fn().mockRejectedValue(new Error("disk"));const existing=[cash("d","a","입금",1)];await expect(saveAccountTransfer(existing,accounts,{sourceAccountId:"a",targetAccountId:"b",amount:1,currency:"KRW",tradedAt:now,memo:""},save)).rejects.toThrow("disk");expect(save).toHaveBeenCalledTimes(1);expect(existing).toHaveLength(1);});
 it("edits both transfer entries while preserving the transfer and trade IDs",()=>{const pair=buildAccountTransfer(accounts,{sourceAccountId:"a",targetAccountId:"b",amount:10,currency:"KRW",tradedAt:now,memo:"old"},now,"pair");const next=updateAccountTransfer(pair,accounts,"pair",{sourceAccountId:"b",targetAccountId:"a",amount:25,currency:"USD",tradedAt:"2026-02-01T00:00:00.000Z",memo:"new"},"2026-02-02T00:00:00.000Z");expect(next.map(item=>item.id)).toEqual(pair.map(item=>item.id));expect(next.every(item=>item.transferId==="pair"&&item.amount===25&&item.currency==="USD"&&item.tradedAt==="2026-02-01T00:00:00.000Z")).toBe(true);expect(getTransferPair(next,"pair").outgoing.accountId).toBe("b");});
 it("soft-deletes both sides with one timestamp",()=>{const pair=buildAccountTransfer(accounts,{sourceAccountId:"a",targetAccountId:"b",amount:10,currency:"KRW",tradedAt:now,memo:""},now,"pair");const deleted=deleteAccountTransfer(pair,"pair","2026-03-01T00:00:00.000Z");expect(deleted.every(item=>item.deletedAt==="2026-03-01T00:00:00.000Z"&&item.updatedAt==="2026-03-01T00:00:00.000Z")).toBe(true);});
 it("rejects missing and mismatched transfer pairs",()=>{const pair=buildAccountTransfer(accounts,{sourceAccountId:"a",targetAccountId:"b",amount:10,currency:"KRW",tradedAt:now,memo:""},now,"pair");expect(()=>validateTransferPairs(pair.slice(0,1))).toThrow("두 건");expect(()=>validateTransferPairs([pair[0],{...pair[1],amount:11}])).toThrow("일치");expect(()=>validateTransferPairs([pair[0],{...pair[1],currency:"USD"}])).toThrow("일치");});
 it("keeps valid transfer cash net zero",()=>{const pair=buildAccountTransfer(accounts,{sourceAccountId:"a",targetAccountId:"b",amount:10,currency:"KRW",tradedAt:now,memo:""},now,"pair");validateTransferPairs(pair);const ledger=buildTradingLedger(pair,accounts);expect(ledger.cashBalances.reduce((sum,item)=>sum+item.balance,0)).toBe(0);});
});
